### ISSUE TITLE
umi3.5.26引入umi-plugin-keep-alive后报错

### ISSUE THREAD

**Issue by xiaoyierle** [alitajs/umi-plugin-keep-alive#66]
## What happens?

> umi3.5.26引入umi-plugin-keep-alive后报错
具体报错信息

```
 ERROR  Failed to compile with 1 errors                      下午4:55:55

 error  in ./src/.umi/umi.ts

Module build failed (from ./node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel-loader/index.js):
Error: [BABEL] /Users/wangzhengyi/workspace/work/umi-test/src/.umi/umi.ts: .0 is not a valid Plugin property
    at /Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:4191:42
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:4180:20)
    at /Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:2687:55
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:4293:3)
    at Generator.next (<anonymous>)
    at step (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:121035:32)
    at evaluateAsync (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:121065:5)
    at Function.errback (/Users/wangzhengyi/workspace/work/umi-test/node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel/bundle.js:120887:7)

 @ multi ./node_modules/_@umijs_preset-built-in@3.5.26@@umijs/preset-built-in/bundled/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/.umi/umi.ts
```
初步排查下来是 ./node_modules/_@umijs_deps@3.5.26@@umijs/deps/compiled/babel-loader/index.js

```
function validatePluginObject(obj) {
  const rootPath = {
    type: "root",
    source: "plugin"
  };
// obj  [
  '/Users/wangzhengyi/workspace/work/umi-test/node_modules/_react-activation@0.11.2@react-activation/babel.js'
]
  Object.keys(obj).forEach(key => {
    const validator = VALIDATORS[key];
    if (validator) {
      const optLoc = {
        type: "option",
        name: key,
        parent: rootPath
      };
      validator(optLoc, obj[key]);
    } else {
      const invalidPluginPropertyError = new Error(`.${key} is not a valid Plugin property`);
      invalidPluginPropertyError.code = "BABEL_UNKNOWN_PLUGIN_PROPERTY";
      throw invalidPluginPropertyError;
    }
  });
  return obj;
}
```

这里的obj应该是对象，但拿到的是个数组，所以报错了

> 最小复现仓库地址 https://github.com/xiaoyierle/umi-keepalive.git

## 复现操作

- cnpm i
- npm start

运行就会报错

> 相关依赖

- **Umi Version**: v3.5.26
- **Node Version**:v14.17.3
- **Platform**: MAC OS 12.3.1

**Comment by xiaoyierle** [comment]
> 刚才有同学修复了，试试beta.33
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月27日(周一) 晚上6:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [alitajs/umi-plugin-keep-alive] umi3.5.26引入umi-plugin-keep-alive后报错 (Issue #66) What happens? umi3.5.26引入umi-plugin-keep-alive后报错 具体报错信息 ERROR Failed to compile with 1 errors 下午4:55:55 error in ./src/.umi/umi.ts Module build failed (from .***@***.******@***.***@@umijs/deps/compiled/babel-loader/index.js): Error: [BABEL] /Users/wangzhengyi/workspace/work/umi-test/src/.umi/umi.ts: .0 is not a valid Plugin property at ***@***.******@***.***@@umijs/deps/compiled/babel/bundle.js:4191:42 at Array.forEach (<anonymous&gt;) at validatePluginObject ***@***.******@***.***@@umijs/deps/compiled/babel/bundle.js:4180:20) at ***@***.******@***.***@@umijs/deps/compiled/babel/bundle.js:2687:55 at Generator.next (<anonymous&gt;) at Function.<anonymous&gt; ***@***.******@***.***@@umijs/deps/compiled/babel/bundle.js:4293:3) at Generator.next (<anonymous&gt;) at step ***@***.******@***.***@@umijs/deps/compiled/babel/bundle.js:121035:32) at evaluateAsync ***@***.******@***.***@@umijs/deps/compiled/babel/bundle.js:121065:5) at Function.errback ***@***.******@***.***@@umijs/deps/compiled/babel/bundle.js:120887:7) @ multi .***@***.******@***.***@@***@***.***/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/.umi/umi.ts 初步排查下来是 .***@***.******@***.***@@umijs/deps/compiled/babel-loader/index.js function validatePluginObject(obj) { const rootPath = { type: "root", source: "plugin" }; // obj [ ***@***.***@react-activation/babel.js' ] Object.keys(obj).forEach(key =&gt; { const validator = VALIDATORS[key]; if (validator) { const optLoc = { type: "option", name: key, parent: rootPath }; validator(optLoc, obj[key]); } else { const invalidPluginPropertyError = new Error(`.${key} is not a valid Plugin property`); invalidPluginPropertyError.code = "BABEL_UNKNOWN_PLUGIN_PROPERTY"; throw invalidPluginPropertyError; } }); return obj; } 这里的obj应该是对象，但拿到的是个数组，所以报错了 最小复现仓库地址 https://github.com/xiaoyierle/umi-keepalive.git 复现操作 cnpm i npm start 运行就会报错 相关依赖 Umi Version: v3.5.26 Node Version:v14.17.3 Platform: MAC OS 12.3.1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

可以了，感谢～
